export const standingsData = [
  {
     "position":1,
     "team_id":53,
     "team_name":"Celtic",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":26,
        "draw":4,
        "lost":3,
        "goals_scored":78,
        "goals_against":19,
        "points":82
     },
     "total":{
        "goal_difference":"59",
        "points":82
     },
     "result":"Championship Round",
     "points":82,
     "recent_form":"WWWWW",
     "status":null
  },
  {
     "position":2,
     "team_id":62,
     "team_name":"Rangers",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":23,
        "draw":7,
        "lost":3,
        "goals_scored":67,
        "goals_against":27,
        "points":76
     },
     "total":{
        "goal_difference":"40",
        "points":76
     },
     "result":"Championship Round",
     "points":76,
     "recent_form":"WWWLW",
     "status":null
  },
  {
     "position":3,
     "team_id":314,
     "team_name":"Hearts",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":16,
        "draw":9,
        "lost":8,
        "goals_scored":48,
        "goals_against":33,
        "points":57
     },
     "total":{
        "goal_difference":"15",
        "points":57
     },
     "result":"Championship Round",
     "points":57,
     "recent_form":"WDWDW",
     "status":null
  },
  {
     "position":4,
     "team_id":282,
     "team_name":"Dundee United",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":10,
        "draw":11,
        "lost":12,
        "goals_scored":31,
        "goals_against":37,
        "points":41
     },
     "total":{
        "goal_difference":"-6",
        "points":41
     },
     "result":"Championship Round",
     "points":41,
     "recent_form":"LDWDD",
     "status":null
  },
  {
     "position":5,
     "team_id":246,
     "team_name":"Ross County",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":10,
        "draw":10,
        "lost":13,
        "goals_scored":45,
        "goals_against":52,
        "points":40
     },
     "total":{
        "goal_difference":"-7",
        "points":40
     },
     "result":"Championship Round",
     "points":40,
     "recent_form":"WWLDW",
     "status":null
  },
  {
     "position":6,
     "team_id":309,
     "team_name":"Motherwell",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":10,
        "draw":10,
        "lost":13,
        "goals_scored":38,
        "goals_against":50,
        "points":40
     },
     "total":{
        "goal_difference":"-12",
        "points":40
     },
     "result":"Championship Round",
     "points":40,
     "recent_form":"LDLWD",
     "status":null
  },
  {
     "position":7,
     "team_id":66,
     "team_name":"Hibernian",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":9,
        "draw":11,
        "lost":13,
        "goals_scored":31,
        "goals_against":37,
        "points":38
     },
     "total":{
        "goal_difference":"-6",
        "points":38
     },
     "result":"Relegation Round",
     "points":38,
     "recent_form":"DDLDL",
     "status":null
  },
  {
     "position":8,
     "team_id":258,
     "team_name":"Livingston",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":10,
        "draw":8,
        "lost":15,
        "goals_scored":35,
        "goals_against":43,
        "points":38
     },
     "total":{
        "goal_difference":"-8",
        "points":38
     },
     "result":"Relegation Round",
     "points":38,
     "recent_form":"WLLLD",
     "status":null
  },
  {
     "position":9,
     "team_id":273,
     "team_name":"Aberdeen",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":9,
        "draw":9,
        "lost":15,
        "goals_scored":38,
        "goals_against":42,
        "points":36
     },
     "total":{
        "goal_difference":"-4",
        "points":36
     },
     "result":"Relegation Round",
     "points":36,
     "recent_form":"LLWDL",
     "status":null
  },
  {
     "position":10,
     "team_id":496,
     "team_name":"St. Mirren",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":8,
        "draw":12,
        "lost":13,
        "goals_scored":30,
        "goals_against":50,
        "points":36
     },
     "total":{
        "goal_difference":"-20",
        "points":36
     },
     "result":"Relegation Round",
     "points":36,
     "recent_form":"LWLLL",
     "status":null
  },
  {
     "position":11,
     "team_id":734,
     "team_name":"St. Johnstone",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":7,
        "draw":9,
        "lost":17,
        "goals_scored":21,
        "goals_against":44,
        "points":30
     },
     "total":{
        "goal_difference":"-23",
        "points":30
     },
     "result":"Relegation Round",
     "points":30,
     "recent_form":"LDWWL",
     "status":null
  },
  {
     "position":12,
     "team_id":284,
     "team_name":"Dundee",
     "round_id":247463,
     "round_name":33,
     "group_id":null,
     "group_name":null,
     "overall":{
        "games_played":33,
        "won":5,
        "draw":10,
        "lost":18,
        "goals_scored":29,
        "goals_against":57,
        "points":25
     },
     "total":{
        "goal_difference":"-28",
        "points":25
     },
     "result":"Relegation Round",
     "points":25,
     "recent_form":"DLLDD",
     "status":null
  }
]

// https://soccer.sportmonks.com/api/v2.0/standings/season/18369?api_token=0S09EPP1DaA8cQzlW9Fl3vTni7YrRQKxGB6rexqmd7CMxv1SYxBXGPGggeFq
// const secretToken = '0S09EPP1DaA8cQzlW9Fl3vTni7YrRQKxGB6rexqmd7CMxv1SYxBXGPGggeFq'
// const seasonId = '18369'